spring:
  application:
    name: product-service-gateway
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    bus:
      enabled: true
      destination: configXchangebus
eureka:
  instance:
    instanceId: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    metadata-map:
      zone: A
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: ${product-service-gateway.eureka.url:http://localhost:9000/eureka}  
      
zuul:
  ignoredPatterns: /authentication/**
  sensitive-headers:
  - Cookie,Set-Cookie
  routes:
    users: /**
    

server:
  port: 9100
