
spring:
  application:
     name: product-service-registry
server:
  port: 9000
eureka:
  instance:
    preferIpAddress: true
    hostname: product-service-registry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    max-threads-for-peer-replication: 0
